import { getAdministrationLayout } from 'components/administration';
import { LinkCard, TileCardList } from 'components/tile-card-list';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { NextPageWithLayout } from 'pages/_app';
import { BsTags } from 'react-icons/bs';
import { FiUsers } from 'react-icons/fi';
import { MdBusiness } from 'react-icons/md';

const administrationCards: LinkCard[] = [
  {
    title: 'Clients',
    description: 'Create, edit, delete clients',
    href: 'clients',
    icon: MdBusiness,
  },
  {
    title: 'Tags',
    description: 'Create, edit, delete hour tags',
    href: 'tags',
    icon: BsTags,
  },
  {
    title: 'Users',
    description: 'View registered users',
    href: 'users',
    icon: FiUsers,
  },
];
const Administration: NextPageWithLayout = () => {
  const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>Timetracky - Administration</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <section>
        <TileCardList cards={administrationCards} />
      </section>
    </>
  );
};
Administration.getLayout = getAdministrationLayout;

export default Administration;
