import Head from "next/head";
import Image from "next/image";
import { trpc } from "utils/trpc";

const Users = () => {
  const { data: users } = trpc.useQuery(["auth.getUsers"]);

  if (!users) {
    return <></>;
  }
  return (
    <>
      <Head>
        <title>Timetracky - Users</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <ul>
        {users.map((u) => {
          const userExtraInfo =
            u.projectCount && u.hourCount
              ? `${u.hourCount} hours across ${u.projectCount} projects`
              : "No hours registered yet";
          return (
            <li
              key={u.id}
              className="flex bg-slate-400 w-80 p-4 rounded-lg gap-3"
            >
              <section className="rounded-full border border-solid bg-black/40 border-gray-400/30">
                <Image
                  src={u.image ?? ""}
                  alt="User image"
                  height={100}
                  width={100}
                  className="rounded-full"
                />
              </section>
              <section className="flex flex-col gap-2 items-center">
                <h1 className="text-2xl font-medium">{u.name}</h1>
                <p className="text-sm">{u.maskedEmail}</p>
                {userExtraInfo ? (
                  <p className="text-sm">{userExtraInfo}</p>
                ) : null}
              </section>
            </li>
          );
        })}
      </ul>
    </>
  );
};

export default Users;
