import Head from "next/head";

const Reports = () => {
  return (
    <>
      <Head>
        <title>Timetracky - Reports</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <section>Reports</section>
    </>
  );
};
export default Reports;
