import Head from 'next/head';

const Reports = () => {
  return (
    <>
      <Head>
        <title>Timetracky - Reports</title>
        <meta content="Generated by create-t3-app" name="description" />
      </Head>
      <section></section>
    </>
  );
};

export default Reports;
