import Head from "next/head";
import { trpc } from "../../utils/trpc";

const Hours = () => {
  const { data: hours } = trpc.useQuery(["timetracky.hours"]);

  return (
    <>
      <Head>
        <title>Timetracky - Hours</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <section>Hours</section>
    </>
  );
};
export default Hours;
